### ISSUE TITLE
Use a faster algorithm for the matrix solver

### ISSUE THREAD

**Issue by edoddridge** [edoddridge/aronnax#1]
Add a faster matrix solver to increase model speed.

**Comment by axch** [comment]
Current plan: Link against LAPACK, which presumably has multithreaded algorithms for matrix inversion.

**Comment by axch** [comment]
Here's the pertinent information on this topic.

The by far most time-consuming computation in n-layer mode is solving for the surface anomaly `etanew`.  This consists of solving the linear system
```
(1)    A etanew = -etastar/dt^2,
```

where A is a linear operator sparsely represented by the array `a`. If we view `etanew` as a single vector laid out column-major, then A is a sparse, banded matrix, with non-zero entries on exactly five diagonals: the main, and the first and nth sub- and super-diagonals, where n is the number of rows in `etanew`.  @edoddridge, is A known to be positive (semi-)definite?

Notably, a full MIM run consists of solving (1) once per timestep with the same matrix A.

The sparse structure of A initially gave me hope that this system could be solved asymptotically quickly, but on further investigation my hopes were ill-founded.  In particular, A cannot be permuted into an O(1)-banded matrix, because any such matrix mixes the elements of the input too slowly [*].

That leaves the following collection of options:
- Status quo: Solve the system by successive over-relaxation, but just speed up the inner loop that multiplies A by the current candidate.
  - This may call for choosing a slightly different SOR scheme, to avoid data dependencies across loop iterations.
  - It may also be appropriate to empirically characterize the number of iterations the SOR scheme tends to use.
  - There may be room to play games with tuning the relaxation schedule across repeated system solves.
- Choose a different iterative method.  Conjugate gradient stuff is well-reputed; the textbook version suggests that A should be positive-definite for that to work, but that modifications for general matrices are available.
  - The high-achiever way to do this involves a (potentially extensive) empirical study of the relative merits of one method or another on "typical" problems, and/or run-time method selection taking advantage the repetitiveness of system solves.
- Treat A as densely banded, and call dgbsv from lapack to solve the system.
  - Con: A dense-banded representation of A will require nx * ny * min(nx,ny) * 8 bytes of memory, most of which will be zeroes.  At 500x500, this is about 1 GB, which is not a problem for modern RAM but will bust out of any believable caches.  (Otherwise, there's some hope that a full MIM run at, say, 400x400x2 may fit entirely in a largish L3 cache.)
  - Pro: Presumably lapack has optimized the bejesus out of the banded matrix solve computation we would be asking for.
  - Pro: Whatever factorization of A lapack will compute internally can be saved and reused across multiple solves.
  - Pro/Con: Lapack's method will presumably not be iterative, but will deterministically take O(nx * ny * min(nx,ny)) time.  Whether this is good or bad depends on how many iterations the iterative methods tend to need.
    - However, Lapack may also internally improve a computed solution by an iterative method applied at the end, I don't know.
  - Pro/Con: Lapack's method will presumably solve the system to the best accuracy it can.  This is good because the answers will be accurate, but bad because the user will not be able to trade accuracy off for performance.  It's also not clear a priori whether Lapack will be more or less accurate than an iterative method, because the roundoff propagation behavior will be completely different.  Presumably lapack has taken some care with this, but a long iteration may still be more accurate.

[*] Proof: Consider repeatedly applying A to a unit vector in the obvious basis for `etanew`, i.e., a 1 at some position x,y and zeroes elsewhere.  In k iterations, non-zeroness will spread to all locations within k of x,y (in the Manhattan metric).  Notably, this is O(k^2) locations.  Now consider repeatedly applying some arbitrary banded matrix B with m bands to (a premutation of) the same unit vector. Each iteration spreads non-zeroness to at most m neighbors of (x,y) in the permuted layout (in each of two directions).  Ergo, in k iterations, non-zeroness will spread to at most 2mk elements; so if m is independent of k, A cannot be a permutation of B.

**Comment by edoddridge** [comment]
I have briefly looked into external libraries for the sparse matrix solve, in particular [Hypre](http://computation.llnl.gov/projects/hypre-scalable-linear-solvers-multigrid-methods/software) and [PETSc](https://www.mcs.anl.gov/petsc/) seem like good candidates.

The main downside that I can foresee to using one of these libraries is that they are explicitly designed for massively parallel computations. As such MPI is integrated into them very deeply.

This is both a positive and a negative. 
- It's a positive because it provides us with a parallel matrix solver. Since this is the most expensive and hardest to parallelise aspect of the model, this is definitely a good thing.
- It's a negative because it bakes in an MPI dependency that we can't easily avoid. We may be able to shield the users from extra configuration, but I think that they will need MPI just to compile.

An additional pro to using one of these, rather than hand coding up our own method, is that they both come with a substantial number of solvers, all of which use a very similar interface. Thus, once we've set the model up to use one, we can set it up to use another without too much work. This would allow us to run the first few time steps with different algorithms and choose the one that is the fastest for that particular simulation. I don't know what sort of differences we could expect, but it might be worth doing.

**Comment by axch** [comment]
On the plus side, if the external library deals with all the MPI goop, that should make it relatively easy for a user to run the model in a distributed setting, thus gaining extra scaling.  I didn't want to think about hand-coding distributed methods for MIM, but if it has already been done, we may be able to just take it.

There is one more negative: I don't know what overhead MPI imposes if one is running on a single machine, so there is some possibility that a tastefully chosen hand-implemented method will be somewhat faster in that regime.

There is a universal method for mitigating the complexity of one's available dependencies: conditional compilation.  `gfortran MIM.f90 -DHYPRE=0` could be set up to compile without Hypre (and use a hand-coded solver).  There is a question of how to choose defaults, but this provides an on-ramp: get it easily, play around, and if you need the extra scale, it's there for you.

**Comment by edoddridge** [comment]
That's definitely a positive.

I don't know either, hopefully it isn't too bad, but if it is, then I guess users will simply use multiple processors.

Thanks for the heads up about the `-D` flag. I've found I need to use a `-cpp` flag to conditionally compile the MPI commands and other fluff - otherwise the purely serial model would depend on MPI, which is silly. This means that I'm making more far-reaching changes to the code than I anticipated.

**Comment by edoddridge** [comment]
I've just pushed the branch on which I've ben working to implement a matrix solver from Hypre.

There are a few things:
 - This branch introduces preprocessing before compilation, so that I can hide all the MPI cruft when the standard model is compiled.
- Despite having an MPI dependency (the external library demands it) this branch still only works on one processor.
- There appears to be a memory issue with one of the external routines - it reads and write outside of the region it is supposed to, and I can't work out why or how to stop it. I think I need to contact them. Valgrind picks this up. The offending write command is `  call HYPRE_StructVectorInitialize(hypre_b, ierr)` to create the RHS vector (I don't understand how this command can be bad and the one to create the x vector can be good - perhaps they are both bad) and the offending read command is `call HYPRE_ParCSRPCGSolve(hypre_solver, hypre_A, hypre_b, hypre_x, ierr)` which solves the system of equations.
- Running the model with valgrind keeps it alive.
- Running the model without valgrind leads to unpredictable behaviour - sometimes it crashes, sometimes is finishes. I expect this is because it is accessing memory that hasn't been properly initialised.
- I added the Hypre library as a submodule. That seemed like the easiest way, but I'm open to suggestions.
- @axch - this still needs work, but I've pushed these commits in the hope that you might have some thoughts about what to do now. Despite narrowing it down to the offending commands, I'm still not sure how to fix it.

**Comment by edoddridge** [comment]
I'm still not sure what caused the issue, but switching to a different solver fixed it :/ Their documentation could use some work...

This branch now runs successfully on a single processor, but it doesn't pass all the tests. I've used a `-cpp` flag to hide the bits of code relating only to the external solver so that they aren't compiled, and thus their dependencies don't matter, when using the reduced gravity physics or the `SOR_solver` subroutine. But, this leads to `gfortran -Wall` complaining about unused variables. Since the subroutines need to be able to deal with these variables, they need to be declared and part of the subroutine call regardless of the mode the model is running in.

If I run the external solver version in the `pytest` script, some of the outputs are sufficiently different from the blessed outputs that the test fails. This is unfortunate.

The Benchmarking scripts shows that this branch is ~2x faster than the internal solver on the larger grids in the beta plane bump configuration. I haven't played around with the different solvers/preconditioners/parameters, so it may be possible to improve this further. Using the Hypre solver, the runtime also appears to be more closely following the `nx`**2 scaling.

![beta_plane_bump scaling](https://cloud.githubusercontent.com/assets/6049169/24421054/ee4085f0-13c2-11e7-9514-b1bd1c6fd693.png)

**Comment by axch** [comment]
Claiming that PR #89 closed this issue was a bit premature, it turns out.  See pending #123, #124.
