### ISSUE TITLE
Inputs placed in input folder get deleted

### ISSUE THREAD

**Issue by edoddridge** [edoddridge/aronnax#138]
`driver.simulate` deletes the input folder before making a new one and putting all of the generated inputs in there. This means any files placed there by the user are deleted before the model loads them in. See [line 62](https://github.com/edoddridge/aronnax/blob/e419283618babfeec8bfb7cdc554e9aa7c07df34/aronnax/driver.py#L62).

Given that `working_directory` doesn't mind creating the directory, it is probably preferable not to delete the input folder every time the model is run. 

Possibly there's a question about protecting users from stale input files, but sending a warning to `stderr` if there are things in the folder seems like a better solution than wiping the folder.

**Comment by axch** [comment]
Sure.  That was just a quick-and-dirty way to make sure that generated inputs would not accidentally be appended to files already in the directory.  The more stylish way to cause that effect would be to consistently open any such files for overwrite rather than append, and just allow other files to coexist.
