### ISSUE TITLE
Can the latency of one model run be improved materially by multithreading?

### ISSUE THREAD

**Issue by axch** [edoddridge/aronnax#47]
Updating the tendencies is a small stencil computation, which parallelizes across threads both (relatively) easily and (quite) well.  No doubt there are also multithreaded matrix inversion algorithms, but I'm not too keen to implement and debug one myself.  Libraries?  OpenBLAS?

Depending on the performance overhead vs ease of installation and compilation, this might actually be a use case for rewriting MIM in Python+Fortran, where the tendency update loops are coded in Fortran and then the matrix inversion is done with a method packaged in scipy (which bottoms out in one or another Fortran library anyway).
- Pro: I know scipy has at least some multithreaded matrix decomposition algorithms.
- Con: It may be more difficult to control the actual numerical method, in case it turns out that the purpose for which MIM needs matrix inversion is specific enough to warrant a different choice than implemented in scipy.

An alternative would be to just parallelize the stencils, which should still show significant benefits in reduced gravity mode, and will at least help some with n-layer mode.

**Comment by edoddridge** [comment]
If a Python+Fortran rewrite can solve both parallelisation and IO issues at once, then it's becoming mighty tempting.

The specifics of the matrix inversion algorithm are of little importance, provided that it is accurate (enough) and fast (enough). The current algorithm was chosen largely for its ease of implementation.

Is the global interpreter lock going to be an issue for parallelising a Fortran+Python version? I remember hearing vague things about Cython being a way to get around the GIL.

In terms of your final point, speed is a much more serious issue for the n-layer version, and I think we should focus our performance efforts on that version (unless the multithreading changes you are suggesting are essentially trivial to implement).

**Comment by axch** [comment]
On the GIL: Essentially, no two individual Python instructions may execute concurrently in the same process.  This kills multithreading parallelism for pure-Python programs, but is not necessarily fatal in this case, because it doesn't interfere with a foreign (to Python) procedure being itself multi-threaded.  In this case, if, say, "compute the tendencies" was still a single Fortran chunk, that chunk could be multi-threaded without interference by Python's GIL.

If we're talking about a rewrite, there are more options to consider:
- Python wrapping Fortran
  - Pro: Status quo.
  - Pro: In principle possible to parallelize to GPUs with PGI CUDA Fortran
- Python+numpy/scipy
  - Pro: No messing around with the Python-Fortran interface (all of that is wrapped by numpy/scipy).
  - Pro: Easy installation and package management.
  - Pro: Access to scipy's optimized matrix inversion
  - Pro: GPUs theoretically accessible with various Python libraries
  - Con: Possibly lots of copies and intermediate arrays, which could become a performance problem
  - Con: May be difficult to parallelize the tendency computations (don't know)
  - Con: Unlikely to be able
- Python+numpy/scipy+ANSI C
  - Con relative to previous: Messing with the C interface; messing with installing packages that contain C extensions.  That's likely to be more annoying than Python dependencies, but probably less annoying than Fortran dependencies.
  - Con relative to next: Not sure about gfortran, but the Intel Fortran compiler produces code that's maybe 25-50% faster than the Intel C compiler, at least on some benchmarks I recall.
  - Pro: C threading libraries are, I think, quite well standardized and easy to ensure the presence of (but I may be mistaken).
  - Pro: GPU access likely to be best debugged, because C is the first language any new technology is made to interoperate with
- Python+numpy/scipy+Fortran
  - Pro: Relatively close to status quo
  - Pro: Likely the fastest we will be able to get the tendency computations to be
- Julia (either all native, or with an inner loop in C or Fortran)
  - Pro: The language itself is both quite fast and quite pleasant to program in
  - Pro: There is a very smooth Python interface
  - Pro: In particular, GPU can be had, at worst through the Python interface
  - Con: I don't actually know it
  - Con: Likely to be viewed as between avant-garde and utterly foreign by the users
  - Con: Don't know how good the packaging is
- Haskell
  - Pro: Would be a lot of fun, and a language I would enjoy practicing GPU libraries from
  - Con: Unlikely to be very friendly to the user community, either for installation or inspection

GPUs are relevant for matrix inversion.  For example, https://pdfs.semanticscholar.org/8ed0/bcbe7e540592981d07740f599793de2ea9b8.pdf

Depending on how heavy the installation dependencies are for using GPUs, and how common they are in the computing infrastructure our users have, it may make sense to ship two different versions of the product, one taking advantage of GPUs present and one not.  Depending on how much they can be made to share, that may or may not be simpler to install and use than one product that switches between using a GPU or not.

**Comment by edoddridge** [comment]
As fun as it would be to rewrite in Haskell or Julia, the fact that neither of us know those languages, and that future users are unlikely to be familiar with them, feels like a deal breaker to me.

All of the high performance computing environments I've used have been CPU only. We're probably aiming more at desktops and local machines rather than big clusters, but my feeling is that if we do want to put lots of effort into performance, then we might be better served by developing the parallelisation to function on clusters, rather than putting that effort into GPU coding.

My preference is definitely for one of the Fortran + Python options, probably Python+numpy/scipy+Fortran. 
Additional pros:
* I'm already familiar with those languages, which will make maintenance much easier for me in the future
* Any future contributors are likely to be familiar with these languages
* It's fairly minimal work - I think the subroutines need only a few minor tweaks to be usable with f2py. The work seems to involve adding `intent` statements to the variable declarations in the subroutines, and, if we want to make things more user friendly, some additional special comments will function as docstrings when the subroutines are being used in Python. See e.g. https://docs.scipy.org/doc/numpy-1.10.0/user/c-info.python-as-glue.html
* we may even be able to have the users interact with the model as a Fortran program, or as a Python program - if almost everything in the model is packaged up into subroutines then the Python wrapping could access them without us rewriting much code. This means that implementing the model in Python may require only writing enough Python to manage the initialisation, the calling of the subroutines, and the IO. This would give future users flexibility to interact with the model in the way they feel most comfortable.
  * N.B. I expect it will take some work to ensure we have equivalent features and a consistent user experience across both implementations.
* any multithreading implemented in the Fortran with openmp should just work when it's called in the Python version. The gfortran compiler appears to have inbuilt openmp support, so I think implementing this will only require the addition of small code snippets around the targeted loops. http://fortranwiki.org/fortran/show/OpenMP

**Comment by axch** [comment]
For the record, I am reasonably proficient in Haskell, but indeed, this doesn't help you or the intended users very much.

Thanks for the pointer to f2py; that helped de-risk this path for me.

**Comment by edoddridge** [comment]
Ah, sorry. I misinterpreted.

**Comment by edoddridge** [comment]
No worries. I think with f2py the Python + numpy/scipy + Fortran option is a pretty low effort pathway that could yield significant benefits.

**Comment by axch** [comment]
New status quo: Hypre depends on MPI, so Aronnax is now an MPI application.  Seems natural to try and use that for parallelism, once #123 and #124 are in reasonable shape.
