### ISSUE TITLE
Rename the model

### ISSUE THREAD

**Issue by edoddridge** [edoddridge/aronnax#63]
Minimalist Isopycnal Model doesn't really roll off the tongue, and MIM is not a particularly searchable acronym.

We've got a bunch of keywords that we can play with:
* Hydrostatic 
* Idealised/simplified (or other synonyms)
* Isopycnal
* Ocean
* Model
* Boussinesq
* Python (maybe)
* Fortran 

This isn't a particularly high priority, but should probably be considered before any serious publicity/release.

**Comment by axch** [comment]
There is also the fad of naming software arbitrarily, rather than by acronym, sometimes going to far as to use personal names: Jenkins, Travis, Asana, Firefox, Ubuntu, Red Hat.  Poseidon might be a bit of an over-reach for something this idealized, but perhaps some lesser classical sea spirit?

**Comment by edoddridge** [comment]
That's a good point. [Nemo](http://www.nemo-ocean.eu/) is already taken, but I like the idea of a vaguely relevant arbitrary name.

**Comment by axch** [comment]
Brainstorming
- Sea spirits:
  - Greek: Poseidon, Aegaeon, Amphitrite, Brizo, Galene, Nereus, Scylla, Tethys, Triton, ...
  - Japanese, Indian, Aztec, Norse, [others](https://en.wikipedia.org/wiki/List_of_water_deities), ...
- Ships (real or [fictional](https://en.wikipedia.org/wiki/List_of_fictional_ships)):
  - Hispaniola, Pequod, Fortune, Merrimack, Nautilus, ...
- Captains (also real or [fictional](https://en.wikipedia.org/wiki/Category:Fictional_ship_captains)):
  - Roberts, Blackbeard, Ahab, Smolett, Flint, [Threepwood](https://en.wikipedia.org/wiki/Guybrush_Threepwood), Jean-Luc, [Maury](https://en.wikipedia.org/wiki/Matthew_Fontaine_Maury), [Galaup](https://en.wikipedia.org/wiki/Jean-Fran%C3%A7ois_de_Galaup,_comte_de_Lap%C3%A9rouse), ...
- Islands
- [Sea monsters](https://en.wikipedia.org/wiki/Sea_monster):
  - Kraken, [Aspidochelone](https://en.wikipedia.org/wiki/Aspidochelone), [Cetus](https://en.wikipedia.org/wiki/Cetus_(mythology)), Tiamat, ...
- Real sea creatures, such as the narwhal
- Non-captain people
  - Aronnax (the narrator of _20,000 Leagues_), Conseil (his servant), Marshall, Verne, [Lesseps](https://en.wikipedia.org/wiki/Ferdinand_de_Lesseps), Hugo, Wells, ...

**Comment by edoddridge** [comment]
Nice list! I was part way through my own. I've removed the double ups.

I'm pretty keen to avoid any deities from current religions - it just feels a bit disrespectful.

Fictional deities.
* [Uinen](https://en.wikipedia.org/wiki/Uinen)
* [Ulmo](https://en.wikipedia.org/wiki/Ulmo)

Other deities:
* [Thalassa](https://en.wikipedia.org/wiki/Thalassa_(mythology))

Ships:
* [Caravel](https://en.wikipedia.org/wiki/Caravel) - a type of small manoeuvrable ship used for exploration by the Portuguese

Other things:
* [Carronade](https://en.wikipedia.org/wiki/Carronade) - a type of lightweight cannon that fires a larger ball over a shorter distance. One needs to pick the right battles to use it in, but used correctly it's very effective.
* [Marlinspike](https://en.wikipedia.org/wiki/Marlinspike) - a tool used by sailors for solving pretty much any problem. Often abbreviated to 'spike'.
* Pelagic - just a cool word that means to do with the open ocean.


My favourites so far are:
* Aronnax
* Narwhal
* Caravel
* Pelagic

**Comment by axch** [comment]
Aesthetically, I like Uinen.  Won't object to Aronnax either.  Narwhal and Caravel seem a little too common, mundane.  But perhaps that's good; "Travis" is a perfectly mundane name, yet effective.  The name should definitely be a noun, otherwise sentences involving it won't scan right.  But perhaps "pelagic" can be nouned -- pelage, pelagus (but perhaps too close to pegasus), pelago (also a shortening of archipelago).

Other considerations:
- The pronunciation should be unambiguous, so two people trying to talk about it to each other will not misunderstand (too often).
- Ideally, the hearing-to-spelling map should be unambiguous too, or at least tight enough for Google's error corrector to fix.
- The Python package and the command-line program are very often named after the project, especially for a project this small; how will those usages scan?  `cd experiment && uinen`; `from aronnax import something, other`; `import pelagus; pelagus.run_experiment(...)`.
  - Actually, Unix command-line tools are often verbs, or nouns with a verb mode argument: `cd`, `make`, `git checkout`; some, like `man` or `grep`, become verbs.  The exceptions seem to be programs whose default is some interactive mode: `sh`, `emacs`, `python`, `firefox`, where the name grammatically serves to summon that creature, which then appears before one.  Hm.  I suppose compilers are all nouns too, and without modal verb arguments: `gcc`, `ifort`, `ghc`, `javac`.
  - That knot can be cut by introducing a modal verb to the main executable: `caravel simulate` vs `caravel help` or (later) `caravel validate` (a set of parameters), etc.
- Do you care whether the model be masculine, feminine, or neuter?

**Comment by edoddridge** [comment]
All good considerations.

I don't have any preference regarding masculine/feminine/neuter.

A slight issue for Aronnax - there is already a PyPI [package under a very similar name](https://pypi.python.org/pypi/arronax/0.06). However, it doesn't seem to be under active development - the latest release was 2014 - so perhaps not a deal breaker.

Same for [caravel](https://pypi.python.org/pypi/caravel) although, that project has since been renamed, so they might be willing to give up the PyPI name.

**Comment by axch** [comment]
It was decided to rename the model and project to Aronnax.  The only piece of that work that has to be done by a specific person is renaming the Github repository, which is now Issue #81.
