### ISSUE TITLE
Consider moving all the large arrays off the stack

### ISSUE THREAD

**Issue by axch** [edoddridge/aronnax#73]
As of PR #72, I encountered a stack overflow problem when running the core.

To reproduce:
- Compile the core with -Ofast,
- Try a run at 700x700x1 or finer resolution,
- Observe segmentation fault.
- If running under valgrind, it reports illegal memory accesses, and recommends increasing the limit on the total stack size, and the stack frame size.  Increasing said limit causes the segmentation fault to go away.
- Compiling with -O2 instead of -Ofast also fixes it.

Diagnosis:
- Arrays of input-specified size are being allocated on the stack.  Thus, if they are large enough, they can overflow limits on stack size or stack frame size.
- The problem manifests in -Ofast but not -O2 because -Ofast includes -fstack-arrays, whose documentation speaks as follows: "Adding this option will make the Fortran compiler put all local arrays, even those of unknown size, onto stack memory.  If your program uses very large local arrays it is possible that you will have to extend your runtime limits for stack memory on some operating systems. This flag is enabled by default at optimization level -Ofast."

What should be done about this?  Options:
- Explicitly code all variable-size arrays as `allocatable`, as the last commit of PR #72 does with the pile of arrays local to `model_run`.
  - Con: Code gets larger and somewhat harder to read.  Memory leaks are not a problem, though, as the standard calls for those arrays being automatically deallocated on exit from the subroutine that declares them.
  - Con: There is some possibility that the allocatable delcaration will impede some optimizations, if gfortran is not smart enough to statically determine that the array is allocated immediately and deallocated only when it goes out of scope.
  - Con: Relatively annoying to measure performance effect of having the arrays on the stack or on the heap.
- Add -fno-stack-arrays to the compilation command.
  - Con: May not be portable to compilers that are not gfortran; but how big of a problem is that?  ifort may well give up to a ~2x speedup, but do we access to it for testing anyway?
  - Pro: Can make the code slightly more legible by reverting said last commit of PR #72.
- Tell the users to raise their stack limits.
  - Con: Complicates adoption.
  - Con: May not be portable across operating systems (Unices have `ulimit`, so that's fine; dunno about Macs, and we're not worrying about Windows anyway).
  - Pro: Presumably -Ofast puts those arrays on the stack for a reason; but then again, if they're that big, it shouldn't much matter where they are allocated.
- Automate raising the stack limit in the wrapper program.
  - Con: Portability across operating systems will be even more brittle than user instructions.

**Comment by edoddridge** [comment]
This is stretching my knowledge of the underlying architecture, but my understanding is that the stack is per thread, so will multithreading essentially deal with this issue? 

Just to check - explicitly allocating the arrays is a portable way of forcing them to be in the heap, rather than the stack? And the only downsides to this are the additional `allocate` commands and the possibility that some compiler optimisations won't be applied?

Finally, 700x700 is quite large, so for now perhaps we can park this as a warning in the documentation and return to it later. Given that running such large grids entirely in serial will take an annoying amount of time, if we get to a stage where this issue only turns up if multithreading is turned off, I'd be happy with that.

**Comment by axch** [comment]
On stacks: Not exactly.  There is a single main stack, which is pertinent before (and after) the threads execute; and then each thread is given a smaller stack so they can call subroutines.  In any case, if single-threaded execution breaks a stack limit, multithreading isn't going to help.

I don't know how portable explicitly allocating the arrays is.  One downside is the additional `allocate` commands, and the possible (but in my opinion unlikely) loss of some optimizations; another is that if we leave the arrays as automatic, the `-fstack-arrays` option of gfortran will make it pretty easy to measure whether there is a performance benefit to having the arrays on the stack---at sizes small enough that they fit (or if the stack limit is raised so they fit).

Re: size: 700x700x1 is about the same amount of memory as 500x500x2 or 400x400x3, which seems more plausible, particularly in n+1/2-layer mode.

**Comment by edoddridge** [comment]
Thanks for the clarification.

In that case, is it worth doing some careful benchmarks with and without the `-fstack-arrays` flag? If we don't see an improvement, perhaps we go for the `allocate` option - it seems to be the most robust solution to me.

**Comment by edoddridge** [comment]
I just reproduced this running a high resolution simulation to make pretty graphics for the landing page. It seems that even with the `allocate` commands the model is able to blow stack limits.

As far as performance issues go, I came across a comment on a [stackoverflow question](http://stackoverflow.com/questions/31433121/difference-between-local-allocatable-and-automatic-arrays) dealing with this issue. The benchmarks in the comment suggest that the benefit from keeping the arrays on the stack is very small for arrays with more than 500 elements. Most configurations of Aronnax, and certainly all the ones in which performance is a serious issue, will have more grid points than that.

I'm now tempted to add the `-fno-stack-arrays` flag to the compilation, put a note in the documentation about it, and remove the allocate commands from the `model_run` subroutine. If I go down that road, I'll play around with the benchmarking script and see how large the impact is before pushing any changes into `master`.

**Comment by edoddridge** [comment]
Running some benchmarks suggests that the performance change for Aronnax is very small, especially when using the Hypre solver, and that the `-fno-stack-arrays` version is very slightly faster. The small effect makes sense, since most of the runtime is spent in Hypre subroutines, which will be unaffected by the change in compiler flag. 

Based on these results I will add the `-fno-stack-arrays` flag to the makefile and revert the allocate commands introduced in the final commit of PR #72. 

![beta_plane_bump_red_grav scaling](https://cloud.githubusercontent.com/assets/6049169/26125342/cdfe75dc-3a4f-11e7-991e-b768b004ebfa.png)
![beta_plane_bump scaling](https://cloud.githubusercontent.com/assets/6049169/26125346/d9514680-3a4f-11e7-9257-5bfae7c2a214.png)
