### ISSUE TITLE
Missing term in SOR matrix solve

### ISSUE THREAD

**Issue by edoddridge** [edoddridge/aronnax#74]
The subroutine `SOR_solver` is missing a term in [two](https://github.com/edoddridge/MIM/blob/17e6a756a80be41a0c4d04a9d8a08732c1974c5f/MIM.f90#L1346) different [lines](https://github.com/edoddridge/MIM/blob/17e6a756a80be41a0c4d04a9d8a08732c1974c5f/MIM.f90#L1364).

The value `a(5,i,j)` should instead be `a(5,i,j) - freesurfFac/dt**2`.

Given that this additional term doesn't change for the duration of the simulation, the additional term can be rolled into `a` in the `derivatives_of_the_depth_field` subroutine.

Confirming that this is affecting the results is a good test case for the automated tests described in #66.

**Comment by axch** [comment]
General comment on filing tickets like this: A Github url involving the word `master` always points to the tip of the `master` branch; so, if someone commits something that changes the number of lines preceding line 1346, the line pointers are liable to shift (unless the Github takes great pains to prevent this).  More reliable (if more cumbersome) is pointing to a specific commit rather than the tip of the branch.

**Comment by edoddridge** [comment]
Thanks for the tip. I've updated it to point at a specific commit.
