### ISSUE TITLE
The simulated momentum is different from the expected momentum (reduced gravity physics)

### ISSUE THREAD

**Issue by edoddridge** [edoddridge/aronnax#99]
The tests being developed for #66 have identified a discrepancy of a few percent between the expected value of the momentum and the simulated momentum. Initial testing suggests that this discrepancy is a function of `dx`, which indicates it may be due to truncation error. This hypothesis should be investigated.

A good way to investigate this is to run a number of simulations with different values of `dx` and examine how the discrepancy changes. If it is a truncation error, then we should see the error decrease in magnitude as `dx` decreases.

There will be a similar ticket for the n-layer version of this problem, which appears to include some additional effect (the discrepancy is a factor of four or so).

**Comment by axch** [comment]
The "bug" label is due to not knowing the cause of the discrepancy.  If we obtain reasonable evidence that it is truncation error, the "bug" label can go away immediately, and this ticket can be closed entirely when that evidence is displayed to the public (ideally in a reasonably automated manner), or when we decide that doing that would be too much work.

**Comment by edoddridge** [comment]
Closed by #120 which shows that the error varies with resolution and displays this information in the documentation.
